spring.application.name=Ecomerce
server.port=8000


spring.config.import=optional:file:.../../.env[.properties], optional:file:./.env[.properties]

spring.jpa.hibernate.ddl-auto=create
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.show-sql=false
spring.docker.compose.enabled=false

spring.datasource.url=${DATABASE_URL}
spring.datasource.username=${DATABASE_USERNAME}
spring.datasource.password=${DATABASE_PASSWORD}

jwt.secret=${JWT_SECRET}
jwt.expiration=${JWT_EXPIRATION:86400000}
jwt.refresh-token-expiration=${REFRESH_TOKEN_EXPIRATION:604800000}


