spring.application.name=Ecomerce
server.port=8000
spring.profiles.active=test


spring.config.import=optional:file:.../../.env[.properties], optional:file:./.env[.properties]


#Database properties
spring.jpa.hibernate.ddl-auto=create
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.show-sql=false
spring.datasource.url=${DATABASE_URL}
spring.datasource.username=${DATABASE_USERNAME}
spring.datasource.password=${DATABASE_PASSWORD}

spring.docker.compose.enabled=false

#Jwt properties
jwt.secret=${JWT_SECRET}
jwt.expiration=${JWT_EXPIRATION:86400000}
jwt.refresh-token-expiration=${REFRESH_TOKEN_EXPIRATION:604800000}

#Stripe properties
stripe.secret-key=${STRIPE_SECRET_KEY}
#Email properties
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=${EMAIL_USERNAME}
spring.mail.password=${EMAIL_PASSWORD}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true


#Redis properties
spring.redis.host=${REDIS_HOST}
spring.redis.port=${REDIS_PORT}
spring.redis.password=${REDIS_PASSWORD}
spring.redis.database=0
spring.redis.timeout=${REDIS_TIMEOUT}
spring.cache.redis.cache-null-values=false
spring.cache.type=redis




