status = WARN
name = PropertiesConfig


appender.console.type = Console
appender.console.name = Console
appender.console.target = SYSTEM_OUT
appender.console.layout.type = JsonLayout
appender.console.layout.complete = false
appender.console.layout.compact = false
appender.console.layout.eventEol = true
appender.console.layout.stacktraceAsString = true
appender.console.layout.objectMessageAsJsonObject = true
appender.console.layout.properties = true


logger.spring.name = org.springframework
logger.spring.level = info
logger.spring.additivity = false
logger.spring.appenderRefs = console
logger.spring.appenderRef.console.ref = Console

logger.hibernate.name = org.hibernate
logger.hibernate.level = info
logger.hibernate.additivity = false
logger.hibernate.appenderRefs = console
logger.hibernate.appenderRef.console.ref = Console

rootLogger.level = info
rootLogger.appenderRefs = console
rootLogger.appenderRef.console.ref = Console
