TRUNCATE TABLE Roles RESTART IDENTITY CASCADE;
TRUNCATE TABLE Permissions RESTART IDENTITY CASCADE; 
TRUNCATE TABLE Cart_item RESTART IDENTITY CASCADE; 
TRUNCATE TABLE Cart RESTART IDENTITY CASCADE; 
TRUNCATE TABLE Products RESTART IDENTITY CASCADE; 
TRUNCATE TABLE Categories RESTART IDENTITY CASCADE; 
TRUNCATE TABLE Users RESTART IDENTITY CASCADE; 
TRUNCATE TABLE Orders RESTART IDENTITY CASCADE; 
TRUNCATE TABLE Orders RESTART IDENTITY CASCADE; 
TRUNCATE TABLE Order_details RESTART IDENTITY CASCADE; 
TRUNCATE TABLE Payments RESTART IDENTITY CASCADE; 





